const ALLOWED_ORIGIN = "https://wertikooo-web.github.io";
const OWNER = "wertikooo-web";
const REPO = "nomad17";
const WORKFLOW = "nomad17.yml";
const MIN_GAP_MS = 60_000;

function json(body,status=200,extraHeaders={}){return new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store","access-control-allow-origin":ALLOWED_ORIGIN,"access-control-allow-methods":"POST, OPTIONS, GET","access-control-allow-headers":"content-type","vary":"Origin",...extraHeaders}})}
function sameSecret(a="",b=""){const aa=new TextEncoder().encode(String(a)),bb=new TextEncoder().encode(String(b));if(aa.length!==bb.length)return false;let diff=0;for(let i=0;i<aa.length;i++)diff|=aa[i]^bb[i];return diff===0}
async function github(env,path,init={}){return fetch(`https://api.github.com${path}`,{...init,headers:{accept:"application/vnd.github+json",authorization:`Bearer ${env.GH_TOKEN}`,"x-github-api-version":"2022-11-28","user-agent":"nomad17-launcher-worker",...(init.headers||{})}})}
async function runs(env,perPage=5){const r=await github(env,`/repos/${OWNER}/${REPO}/actions/workflows/${WORKFLOW}/runs?per_page=${perPage}`);if(!r.ok)throw new Error(`GitHub runs lookup failed: ${r.status}`);return (await r.json()).workflow_runs||[]}
async function latestRun(env){return (await runs(env,1))[0]||null}
async function jobState(env,runId){const r=await github(env,`/repos/${OWNER}/${REPO}/actions/runs/${runId}/jobs?per_page=10`);if(!r.ok)return null;const jobs=(await r.json()).jobs||[],job=jobs[0]||null;if(!job)return null;const active=(job.steps||[]).find(s=>s.status==="in_progress")||[...(job.steps||[])].reverse().find(s=>s.status==="completed");return {job_status:job.status,job_conclusion:job.conclusion,current_step:active?.name||null,steps:(job.steps||[]).map(s=>({name:s.name,status:s.status,conclusion:s.conclusion}))}}
async function dispatch(env,inputs={}){const latest=await latestRun(env);if(latest?.created_at){const age=Date.now()-Date.parse(latest.created_at);if(age>=0&&age<MIN_GAP_MS){const wait=Math.max(1,Math.ceil((MIN_GAP_MS-age)/1000));return {limited:wait}}const r=await github(env,`/repos/${OWNER}/${REPO}/actions/workflows/${WORKFLOW}/dispatches`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({ref:"main",inputs})});if(r.status!==204){const detail=await r.text();throw new Error(`GitHub отказал в запуске (${r.status}): ${detail.slice(0,300)}`)}return {ok:true,accepted_at:new Date().toISOString()}}
export default{async fetch(request,env){const origin=request.headers.get("Origin")||"";if(request.method==="OPTIONS"){if(origin!==ALLOWED_ORIGIN)return json({ok:false,error:"Origin denied"},403);return json({ok:true})}const url=new URL(request.url);if(request.method==="GET"&&url.pathname==="/health")return json({ok:true,service:"nomad17-launcher",min_gap_seconds:60,missions:true,status_api:true});if(request.method==="GET"&&url.pathname==="/status"){if(origin&&origin!==ALLOWED_ORIGIN)return json({ok:false,error:"Origin denied"},403);try{const after=url.searchParams.get("after"),all=await runs(env,8);let run=all[0]||null;if(after){const t=Date.parse(after)-5000;run=all.find(x=>Date.parse(x.created_at)>=t)||null}if(!run)return json({ok:true,found:false});const job=await jobState(env,run.id);return json({ok:true,found:true,run:{id:run.id,status:run.status,conclusion:run.conclusion,created_at:run.created_at,run_started_at:run.run_started_at,updated_at:run.updated_at,html_url:run.html_url,event:run.event,attempt:run.run_attempt},job})}catch(e){return json({ok:false,error:e.message||"Status error"},502)}}if(request.method!=="POST"||!["/run","/mission"].includes(url.pathname))return json({ok:false,error:"Not found"},404);if(origin!==ALLOWED_ORIGIN)return json({ok:false,error:"Origin denied"},403);if(!env.GH_TOKEN||!env.RUN_PASSWORD)return json({ok:false,error:"Worker secrets are not configured"},503);let body;try{body=await request.json()}catch{return json({ok:false,error:"Bad JSON"},400)}if(!sameSecret(body?.password,env.RUN_PASSWORD))return json({ok:false,error:"Неверная фраза"},401);try{let inputs={};if(url.pathname==="/mission"){const mission=String(body?.mission||"").trim().slice(0,1500);if(mission.length<12)return json({ok:false,error:"Опиши задачу чуть подробнее."},400);inputs={mission,research_depth:"deep"}}const result=await dispatch(env,inputs);if(result.limited)return json({ok:false,error:`Nomad17 недавно запускался. Подожди ${result.limited} сек.`,retry_after:result.limited},429,{"retry-after":String(result.limited)});return json({ok:true,message:url.pathname==="/mission"?"Исследовательская миссия запущена":"Nomad17 проснулся",accepted_at:result.accepted_at})}catch(e){return json({ok:false,error:e.message||"Launcher error"},502)}}};
